using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

using MigrationEngine.Configuration;
using MonikerProviders;

namespace MigrationEngine.Tasks
{
    /// <summary>
    /// Base class for all migration tasks.
    /// </summary>
    public abstract class MigrationTask : IMigrateTask
    {
        /// <summary>
        /// Descriptive name of an individual instance of a migration task.
        /// </summary>
        /// <value>The name.</value>
        [XmlAttribute()]
        public String Name { get; set; }

        [XmlIgnore()]
        private MonikerStore _monikerStoreField;
        protected MonikerStore MonikerStore
        {
            get
            {
                // Doing a lazy initialization in the getter guarantees that
                // the moniker store isn't loaded until the task is ready to use it.
                // This is important for the case where a task uses monikers which
                // were generated by an earlier task.
                if (_monikerStoreField == null)
                {
                    MigrationEngineSection config = (MigrationEngineSection)ConfigurationManager.GetSection("MigrationEngine");
                    string storeProvider = config.MonikerStoreProviderName.Value;
                    _monikerStoreField = new MonikerStore(storeProvider);
                }
                return _monikerStoreField;
            }
        }

        /// <summary>
        /// This is the main method for implementing a migration task.
        /// An instance of IMigrationLog is provided for logging the
        /// progress through the list of task items.
        /// </summary>
        /// <param name="logger">IMigrationLog object for recording task progress.</param>
        abstract public void Doit(IMigrationLog logger);

        protected string LookupCommunityName(string key)
        {
            string community = null;

            if (string.IsNullOrEmpty(key))
                throw new InvalidCommunityNameException("Community lookup key must not be null or empty.");

            MigrationEngineSection lookup = (MigrationEngineSection)ConfigurationManager.GetSection("MigrationEngine");
            if (lookup == null)
                throw new ConfigurationException("Unable to load MigrationEngine settings section.");

            community = lookup.Community[key].Name;
            if (lookup == null)
                throw new InvalidCommunityNameException(string.Format("No community found for key '{0}'.", key));

            return community;
        }
    }
}
